name: Compartir datos entre jobs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore GitHub-Actions-Linkedin.sln
    - name: Build
      run: dotnet build GitHub-Actions-Linkedin.sln --no-restore
    - name: Test
      run: dotnet test GitHub-Actions-Linkedin.sln --no-build --verbosity normal
    - name: Publish
      run: dotnet publish GitHub-Actions-Linkedin.sln --configuration Release --output publish
    - name: Subir datos
      uses: actions/upload-artifact@v4
      with:
        path: publish
  storage:
    name: Almacenamiento
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Descargar datos
      uses: actions/download-artifact@v4
      with:
        path: publish
    - name: Muestra el contenido del artefacto
      shell: bash
      run: ls publish -R
