name: Execute Remote Workflow

on:
  workflow_dispatch:  # Para ejecutar manualmente

jobs:
  execute_workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: ./actions/action.yaml  # Ruta al flujo de trabajo
