name: Execute Remote Workflow

on:
  workflow_dispatch:  # Para ejecutar manualmente

jobs:
  execute_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutar yaml remoto
        run: |
               # La ruta del archivo YAML, asegúrate de que sea la ruta correcta
               #  `../../mi-archivo-yaml.sh` si el archivo YAML está en el directorio raíz de 
               #  tu repositorio y no dentro de la carpeta `.github/workflows`
               bash ../../actions/action.yaml'
