name: GitHub Token 2

on:
  workflow_dispatch:

env:
  SOLUTION_PATH: GitHub-Actions-Linkedin.sln
  DOCKERFILE_PATH: wpm/WisdomPetMedicine.Api/Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore $SOLUTION_PATH
    - name: Build
      run: dotnet build $SOLUTION_PATH --no-restore
    - name: Test
      run: dotnet test $SOLUTION_PATH --no-build --verbosity normal
  docker:
    name: Contenerización con Docker y .NET
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v3
    - name: docker build
      run: docker build wpm --file $DOCKERFILE_PATH --tag chema1973/github-actions-esencial:${{ github.run_number }}

    - uses: docker/login-action@v2
      name: Log in en Docker Hub
      with:
        username: USUARIOINCORRECTO
        password: PASSWORDINCORRECTO

    - name: Crear un issue con el API REST
      if: ${{ failure() }}
      with:
          title: "Build failed"
          body: "The build process failed. Please investigate the logs."
          assignees: ${{ github.actor }}
          labels: "bug"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
