name: Matriz de configuraciones y versión de .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
        dotnetversion: [8.0.x, 9.0.x]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnetversion }}
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore WisdomPetMedicine.sln
    - name: Build
      run: dotnet build WisdomPetMedicine.sln --configuration ${{ matrix.configuration }} --no-restore
