name: Runners hospedados - Linux - Docker

on:
  workflow_dispatch:
    
jobs:
  docker:
    name: Contenerización con Docker y .NET
    runs-on: [self-hosted, linux]
    steps:
    - uses: actions/checkout@v3
    - name: docker build
      run: docker build wpm --file wpm/WisdomPetMedicine.Api/Dockerfile --tag github-actions-esencial:runner
