# Este ha funcionado con el runner de windows
# Para evitar fallos, Docker Desktop tenía que estar abierto:
# ERROR: error during connect: Head "http://%2F%2F.%2Fpipe%2FdockerDesktopLinuxEngine/_ping": open //./pipe/dockerDesktopLinuxEngine: The system cannot find the file specified.

# Ha creado la imagen en Docker Desktop de "github-action-esencial - runner - d6dde0a3a1e4 - 11 minutes ago - 328.67 MB"

name: Runners hospedados - Docker

on:
  workflow_dispatch:
    
jobs:
  docker:
    name: Contenerización con Docker y .NET
    runs-on: [self-hosted, windows]
    steps:
    - uses: actions/checkout@v3
    - name: docker build
      run: docker build wpm --file wpm/WisdomPetMedicine.Api/Dockerfile --tag github-actions-esencial:runner
