name: Runners hospedados - Docker

on:
  workflow_dispatch:
    
jobs:
  docker:
    name: Contenerización con Docker y .NET
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v3
    - name: docker build
      run: docker build wpm --file wpm/WisdomPetMedicine.Api/Dockerfile --tag github-action-esencial:${{ github.event.inputs.tag }}
